version: "3"
virtualbrowsers:
- name: rancher
  url: https://rancher.manager.${_SANDBOX_ID}.instruqt.io
virtualmachines:
- name: manager
  image: suse/rancher-2-12-2
  machine_type: n1-standard-2
  allow_external_ingress:
  - high-ports
  - http
  - https
  environment:
    DOWNSTREAM_CLUSTERS: production
- name: production
  image: suse/k3s-1-32
  machine_type: n1-standard-4
  allow_external_ingress:
  - high-ports
  - http
  - https
  environment:
    MANAGER_HOSTNAME: manager
