#!/bin/bash
# Collection of functions to manage Rancher lifecycle

#######################################
# Installs Rancher Prime with a certificate generated by a cluster issuer
# Arguments:
#   Version
#   Number of replicas
#   Hostname
#   Cluster issuer name (managed by cert-manager)
# Examples:
#   rancherprime_install_withcertmanagerclusterissuer "2.8.2" rancher.random_string.geek
#######################################
rancherprime_install_withcertmanagerclusterissuer() {
  local version=$1
  local hostname=$2
  local create_ingress=${3:-true}

  if [[ "$create_ingress" == "true" ]]; then
    ingress_opts="--set ingress.extraAnnotations.'cert-manager\.io/cluster-issuer'=letsencrypt-prod --set ingress.ingressClassName=nginx --set ingress.tls.source=secret --set ingress.tls.secretName=rancher-tls"
  fi
  echo "Installing Rancher..."
  helm repo add rancher-prime https://charts.rancher.com/server-charts/prime
  helm repo update
  helm upgrade --install rancher rancher-prime/rancher --namespace cattle-system --create-namespace \
    --version ${version} \
    --set replicas=1 \
    --set hostname=${hostname} \
    ${ingress_opts} \
    --set agentTLSMode="system-store"
  kubectl wait pods -n cattle-system -l app=rancher --for condition=Ready --timeout=180s
  echo "Waiting for Rancher web app to be running with a valid certificate..."
  if [ "$hostname" == "rancher.test.host" ]; then
    echo "Skipping certificate validation for hostname ${hostname}"
  else
    kubectl wait --for=condition=Ready --timeout=300s certificate -n cattle-system rancher-tls
  fi
}

rancher_create_ingress() {
  local ingressClass=$1
  local hostname=$2

  echo "Creating Ingress for Rancher..."
  kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    app: rancher
  name: rancher
  namespace: cattle-system
spec:
  ingressClassName: ${ingressClass}
  rules:
  - host: ${hostname}
    http:
      paths:
      - backend:
          service:
            name: rancher
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - ${hostname}
    secretName: rancher-tls
EOF
}

#######################################
# Do the first log in Rancher (will update admin password and set server URL)
# Arguments:
#   Rancher URL (starting with http:// or https://)
#   new password
# Examples:
#   rancher_first_login MyNewPassword
#######################################
rancher_first_login() {
  local rancherUrl=$1
  local newPassword=$2

  echo 'Do first login on Rancher...'
  BOOTSTRAP_PASSWORD=$(kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ "\n" }}')
  echo "DEBUG BOOTSTRAP_PASSWORD=${BOOTSTRAP_PASSWORD}"
  LOGIN_TOKEN=$(rancher_login_withpassword $rancherUrl 'admin' $BOOTSTRAP_PASSWORD)
  echo "DEBUG LOGIN_TOKEN=${LOGIN_TOKEN}"
  rancher_update_password $rancherUrl $LOGIN_TOKEN $BOOTSTRAP_PASSWORD $newPassword
  rancher_update_serverurl $rancherUrl
}

#######################################
# Waits for Rancher CAPI to be ready (for cluster creation in particular)
# Arguments:
#   None
# Examples:
#   rancher_wait_capiready
#######################################
rancher_wait_capiready() {
  _counter=0
  while [[ $_counter -lt 25 ]]; do
    status=$(kubectl get deployment capi-controller-manager -n cattle-provisioning-capi-system -o jsonpath='{.status.conditions[?(@.type=="Available")].status}' 2>/dev/null)
    if [ "$status" == 'True' ]; then
      echo 'Deployment capi-controller-manager is available'
      break
    fi
    sleep 10
    ((_counter++))
    echo "Waiting for capi-controller-manager to become available... attempt ${_counter}/25"
  done
  if [[ $_counter -eq 25 ]]; then
    echo 'Deployment capi-controller-manager is not available'
    kubectl get deployment capi-controller-manager -n cattle-provisioning-capi-system -o jsonpath='{.status}'
    exit 1
  fi
  _counter=0
  while [[ $_counter -lt 25 ]]; do
    if [[ ! $(kubectl get endpoints capi-webhook-service -n cattle-provisioning-capi-system -o jsonpath='{.subsets}' 2>/dev/null) == '' ]]; then
      echo 'Endpoint is ready'
      break
    fi
    sleep 10
    ((_counter++))
    echo "Waiting for endpoint capi-webhook-service to be ready... attempt ${_counter}/25"
  done


  echo 'Service capi-webhook-service is ready'
}
